- name: Install default PHP-7.1 set
  yum: name={{ item }} state=present
  with_items:
   - php71.x86_64
   - php71-bcmath.x86_64
   - php71-cli.x86_64
   - php71-common.x86_64
   - php71-fpm.x86_64
   - php71-gd.x86_64
   - php71-gmp.x86_64
   - php71-intl.x86_64
   - php71-mbstring.x86_64
   - php71-mcrypt.x86_64
   - php71-mysqlnd.x86_64
   - php71-opcache.x86_64
   - php71-pdo.x86_64
   - php71-pecl-redis.x86_64
   - php71-soap.x86_64
   - php71-process.x86_64
   - php71-xml.x86_64
   - php71-xmlrpc.x86_64

- name: Configure and Restart PHP-FPM
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  notify: restart php-fpm

- name: PHP-FPM autostart
  service: name=php-fpm state=started enabled=yes
