- name: Install latest Nginx from official repo
  yum: name={{ item }} state=present
  with_items:
        - nginx

- name: Configure and Restart Nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Configure Nginx Vhost
  template: src=vhost.conf.j2 dest=/etc/nginx/conf.d/vhost.conf

- name: Nginx autostart
  service: name=nginx state=started enabled=yes
